security:
    encoders:
        App\Entity\User:
            algorithm: auto

    role_hierarchy:
        ROLE_EMPLOYEE: ROLE_EMPLOYEE
        ROLE_ADMIN: [ ROLE_USER, ROLE_EMPLOYEE, ROLE_ALLOWED_TO_SWITCH ]

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            provider: app_user_provider
            pattern: ^/
            anonymous: true
            form_login:
                default_target_path: office_list
                login_path: app_login
                check_path: app_login
            logout:
                path: app_logout
                target: app_login
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /
                # where to redirect after logout
                # target: app_any_route
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/forgot-password, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/techm, roles: IS_AUTHENTICATED_FULLY }
#        - { path: ^/$, roles: IS_AUTHENTICATED_FULLY }